"""modified product fields to include upload 

Revision ID: 7966f1bc575c
Revises: c9f918fae292
Create Date: 2025-12-01 13:11:16.754137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7966f1bc575c'
down_revision = 'c9f918fae292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_filepath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('document_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('document_type')
        batch_op.drop_column('document_size')
        batch_op.drop_column('document_filepath')
        batch_op.drop_column('document_filename')

    # ### end Alembic commands ###
