"""Add product_type to Product model

Revision ID: c9f918fae292
Revises: 3933e078b99e
Create Date: 2025-11-27 10:00:07.054027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f918fae292'
down_revision = '3933e078b99e'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'products',
        sa.Column('product_type', sa.String(10), nullable=False, server_default='bosa')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
